# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160229_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='vacia', max_length=150),
        ),
    ]
